### PR TITLE
use binding in manifest for the env vars

### PR DESCRIPTION
**Pull request by ghost**
**Do**

The idea is to bring the ability to the user to use environment variables coming from the host of the Estafette.

**How**

In your manifest when you declare a pipeline:

```yaml
build:
    env:
      HOST_ENV_1: ${HOST_ENV_1}
    image: golang:1.9.0-alpine3.6
    workDir: /go/src/github.com/estafette/${ESTAFETTE_LABEL_APP}
    commands:
    - echo $HOST_ENV_1
    - apk --update add git
    - go test -v `go list ./... | grep -v /vendor/`
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_LABEL_APP} .
```

**Test**

I added one test case but it requires an environment variable.

**More**

I think it is subject to discussion but currently, it could help us.

### CODE REVIEW

**Comment by JorritSalverda** [comment]
Currently all environment variables prefixed with `ESTAFETTE_` are passed in to all the containers used in the pipelines. In the ci-builder there are no notable other environment variables that seem worth passing. Perhaps the go.cd based one has - `Dockerfile.gocd`, but the Estafette one hardly does.

What is it you want to pass on to the container? There might be a cleaner way to solve it.

**Comment by ghost** [comment]
Yes I saw it. But I don't want my programme to explicitly refer to the Estafette. I want to be able to setup the container where the estafette is running for having generic manifest

**Comment by JorritSalverda** [comment]
Let me think. What I do in a couple of places is substitute environment variables with the following code:

```
os.Expand(p.WorkingDirectory, dr.envvarHelper.getEstafetteEnv)
```

However this only replaces `ESTAFETTE_` environment variables. I'm trying to remember if there's any sensible reason not to replace any environment variable.

**Comment by ghost** [comment]
As an example, we could look at how Serverless is doing it in their manifest. They also support a reference to a file in the host. Its properties are then exposed as variables in the manifest

**Comment by JorritSalverda** [comment]
Yes, I think it's sensible to replace any environment variable. But let's make a dedicated `substituteEnvvars` method in the `EnvvarHelper` interface instead of piggy backing it on top of `overrideEnvvars`. That feels cleaner to me, and keeps `overrideEnvvars` focused on the hierarchy of replacing outer envvars with ones closer to the pipeline step.

We can then call it after

```
// combine and override envvars
combinedEnvVars := dr.envvarHelper.overrideEnvvars(envvars, p.EnvVars, extensionEnvVars)
```

with

```
// substitute used envvars in the values with their actual value
combinedEnvVars := dr.envvarHelper.substituteEnvvars(combinedEnvVars)
```

Can you code this in this PR?

Later on we can look at defining "global" environment variables in the manifest as well, that can be used in multiple steps and deployments, but haven't settled on what it should look like yet.

**Comment by ghost** [comment]
Yes sure. I will do it. I close this one for now

**Pull request closed without merging**
